### ISSUE TITLE
[Keys] Remove all cli functionality from eris-keys save for `serve` (to match db)

### ISSUE THREAD

**Issue by compleatang** [hyperledger/burrow#338]
@compleatang commented on [Fri Aug 26 2016](https://github.com/eris-ltd/eris-keys/issues/64)

**Problem** -- keys is a server. It should be built and tested like one. 

**Solution** -- 
- [ ] remove the crutch of the cli interface
- [ ] refactor the server (audit)
- [ ] better test suite
- [ ] cleanly separate the client library for the server's api from the rest of the repository
