### ISSUE TITLE
Implement remote signing for Tendermint validator

### ISSUE THREAD

**Issue by benjaminbollen** [hyperledger/burrow#522]
NOTE: This is a progress tracking epic; new issues will be added as work continues.

Work proposal:
- [ ] https://github.com/eris-ltd/eris-db/issues/523 implement a private validator in `eris-db/consensus` that signs locally (ie not a remote signer yet):
  - provide the basis for a fall-back mechanism; 
  - move signing from tendermint into eris-db
- [ ] provide `eris-db/crypto`
- [ ] [...]
- [ ] provide benchmarking for tendermint local signing; eris-db local signing and remote signing

**Comment by VoR0220** [comment]
Just make this "move keys into eris-db"
